language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install libgeos-dev libgdal-dev valgrind

script:
  - cargo test
  - cargo run --example verbose_example
  - cargo run --example prepared_geom
  - cargo run --example from_geo
  # run valgrind to check that there are no memoryleaks
  - valgrind --leak-check=full --error-exitcode=42 target/debug/deps/geos-6c424d75d3633a62
  - valgrind --leak-check=full --error-exitcode=42  ./target/debug/examples/from_geo
  - valgrind --leak-check=full --error-exitcode=42  ./target/debug/examples/verbose_example
  - valgrind --leak-check=full --error-exitcode=42  ./target/debug/examples/prepared_geom
