[package]
name = "geos"
version = "0.0.1"
authors = ["<matthieu.viry@cnrs.fr>"]
license = "MIT"
repository = "https://github.com/mthh/rust-geos"

[dependencies]
libc = "*"
num = "*"
geo = ">=0.4,<=0.6"
failure = "0.1"
failure_derive = "0.1"
